name: '💡 Feature Request'
title: '[Feature Request] '
description: 'Suggest an idea'
labels: ['type: feature', 'state: triage']

body:
  - type: 'textarea'
    id: 'problem'
    attributes:
      label: 'Describe the problem/motivation'
      description: 'A clear description of the problem this feature would solve'
      placeholder: "It's an issue that..."
    validations:
      required: true

  - type: 'textarea'
    id: 'solution'
    attributes:
      label: "Describe the solution you'd like"
      description: 'A clear description of what change you would like'
      placeholder: 'I would like to...'
    validations:
      required: true

  - type: 'textarea'
    id: 'alternatives'
    attributes:
      label: 'Alternatives considered'
      description: "Any alternative solutions you've considered"

  - type: 'textarea'
    id: 'context'
    attributes:
      label: 'Additional context'
      description: 'Add any other context about the problem here.'
